# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e74897109d595988042580bc16affb5031faac73b540ce2c89cff3f723afca26110a2ff228d10b38e23445013d20d1219bfe7ff78674b8a287f65ff7b0b94ff

test:
  secret_key_base: 3b4c5576f8228f97f908d0f2c418b3d9cf65a09aaabeda4025c3efb8711b0f80a60de0efa2083f4ff8220513f4cade9d68fa30aa574f651c0604eea9572d88f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
